Added zone check - If multiple records are being used - added a check that all records   have the same zone. The script will now exit if this is not the case - If it is desired to update records from multiple zones, it is best   call the script with a different config file using the -c option - This is because different zones require different API keys on the   Luadns.com side

diff --git a/luadns-ddns b/luadns-ddns
--- a/luadns-ddns
+++ b/luadns-ddns
@@ -44,6 +44,9 @@ main() {
   # Just using the 1st one for now...
   get_zone_name "${record_names[0]}"
 
+  # Check all Records have the same zone. Exit if they do not
+  check_record_zones
+
   # Check for Forced Update
   check_for_forced_update
 
@@ -390,7 +393,7 @@ print_greeting() {
   echo ""
 }
 
-# Get and Check the Zone Name is hosted at Luadns.com
+# Get the Zone Name
 get_zone_name() {
   local fqdn="${1}"
 
@@ -407,6 +410,21 @@ get_zone_name() {
  
   # Pick Everything after the 2nd last "." to get the root-domain
   zone_name=$( echo "${fqdn}" | awk -F "." '{ printf $(NF-1)"."$NF}')
+}
+
+# Check the Zone name associated with all records is the same. Start from 2nd record
+check_record_zones() {
+  if [ $N_records -gt 1 ]; then
+    for i in $(seq 1 1 $((N_records-1))); do
+      local zone_check=$(echo "${record_names[$i]}" | awk -F "." '{ printf $(NF-1)"."$NF}')
+      if [ "${zone_check}" != "${zone_name}" ]; then
+        echo " + ERROR: Zone Name for Record: ${record_names[$i]} is different from ${record_names[0]}"
+        echo "          To update records on a different zone it is recommended to call the script"
+        echo "          with a different config file using the -c|--config option - Exiting"
+        exit 1
+      fi
+    done
+  fi
 }
 
 # Check the Zone is hosted at Luadns.com
