Update debian maintainer scripts

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/sh -e
 
 ###################################
 # Debian Maintainer Postinst Script
@@ -11,14 +11,11 @@
 #
 # Also ensures the permissions are updated on an additional working
 # directory. Usually - /var/lib/${package_name} if being used
-#
-# Notes: Require a dependency in debian/control for awk, coreutils
-# and wtmpdb
 ###################################
 
-# Recommended by Debian Policy Manual Here:
-# https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html
-set -e
+# Source debconf library.
+. /usr/share/debconf/confmodule
+db_version 2.0
 
 # Script Variables
 package_name="luadns-ddns"
@@ -26,30 +23,25 @@ dropin_dir="/etc/systemd/system/${package_name}.service.d"
 dropin_file="${dropin_dir}/user.conf"
 working_dir="/var/lib/${package_name}"
 
+# Action
+action="$1"
+
 ###################################
 # Main Function
 ###################################
 main() {
-  # Check for Configure Argument
-  if [ "${1}" == "configure" ]
+  # Check for Configure Argument (single = only...)
+  if [ "$action" = "configure" ]
   then
     # Print Banner
-    #print_banner "${2}"
-    print_banner
+    print_banner "$@"
 
-    # Check that systemd is present by looking for the systemctl
-    # command. If it ins't - Exit. This is to ensure the install
-    # can be completed on a Debian based distro that doesn't have
-    # systemd
-    if [ -z $(which systemctl) ]
-    then
-      echo "Systemd not present - Not attempting any config"
-      exit 0
-    fi
+    # Now call debconf and get the value of the systemd_user
+    # and systemd_group that the user was prompted for.
+    get_group_and_user
 
-    # Prompt the User for the username that the service will run as
-    # and generate the dropin file accordingly
-    generate_dropin_file "${1}"
+    # Generate Drop-In File
+    generate_dropin_file
 
     # Exit with Success
     exit 0
@@ -63,140 +55,115 @@ main() {
 ###################################
 # Other Functions
 ###################################
-# Generate Drop In File with a Specific User and Group
-write_dropin_file() {
-  local user1="${1}"
-  local group1="${2}"
-
-  # Create Drop-In File - Comment Out both Lines
-  # and leave fields empty if root was selected
-  if [ "${user1}" == "root" ]
-  then
-    echo "#[Service]" > "${dropin_file}"
-    echo "#User=" >> "${dropin_file}"
-    echo "#Group=" >> "${dropin_file}"
-  else 
-    echo "[Service]" > "${dropin_file}"
-    echo "User=$user1" >> "${dropin_file}"
-    echo "Group=$group1" >> "${dropin_file}"
-  fi
-}
-
 # Print Banner
 print_banner() {
-  echo ""
   echo "###########################"
-  if [ -z "${1}" ]; then
+  if [ -z "$2" ]; then
     echo "# Luadns-DDNS"
   else
-    echo "# Luadns-DDNS Version:" "${1}"
+    echo "# Luadns-DDNS Version:" "$2"
   fi
   echo "###########################"
 }
 
-# Print Brief Message on how to start service
-print_instructions() {
-  echo "###########################"
-  echo "Done: ${dropin_file} generated with the following:"
-  echo "  User=${username}"
-  echo "  Group=${groupname}"
-  if [ "${permissions_updated}" == "yes" ]; then
-    echo "and permissions updated on: ${working_dir}"
-  fi
-  echo "Now setup the config file, see the following manpage:"
-  echo " "${package_name}"(1) or \$ man "${package_name}""
-  echo "When done, start the timer like so to automate:"
-  echo "  $ systemctl start ${package_name}.timer"
-  echo ""
+###################################
+# Get Group and User
+###################################
+get_group_and_user() {
+
+  # Get the User Name
+  db_get luadns-ddns/systemd_user || true
+  systemd_user="$RET"
+
+  # Get the Group Name
+  db_get luadns-ddns/systemd_group || true
+  systemd_group="$RET"
 }
 
-# Get User and Group for Drop in File
+###################################
+# Generate the Drop-In File
+###################################
 generate_dropin_file() {
 
-  # Check for existance of user drop in file, no prompting if
-  # already present
-  if [ ! -f "${dropin_file}" ]
+  # Check if the user is blank, if this is the case,
+  # use root
+  if [ -z "$systemd_user" ]
   then
-    # Find Last logged in non-root user
-    if [ ! -z $(which wtmpdb) ]
+    systemd_user="root"
+    systemd_group="root"
+  fi
+
+  # Check if the group is empty, if it is,
+  # default to the default group for the user
+  if [ -z "$systemd_group" ]
+  then
+    systemd_group=$(groups "$systemd_user" | awk '{print $3}')
+  fi
+
+  # Print Out the Service User/Group
+  echo "Service User: $systemd_user"
+  echo "Service Group: $systemd_group"
+  echo "To change run $ dpkg-reconfigure ${package_name}"
+
+  # If the dropin directory doesn't exist - create it
+  if [ ! -d "$dropin_dir" ]
+  then
+    mkdir "$dropin_dir"
+  fi
+
+  # Now Check if the drop-in file exists
+  if [ -f "$dropin_file" ]
+  then
+    # Get the Group and User from the Drop-In file
+    existing_user="$(grep "^User=" "$dropin_file" | sed 's/User=//;s/ *$//')"
+    existing_group="$(grep "^Group=" "$dropin_file" | sed 's/Group=//;s/ *$//')"
+
+    # Check if the User and the Group are different, if so
+    # Re-Generate the drop-in file and reload systemd
+    if [ "$existing_user" != "$systemd_user" ] || [ "$existing_group" != "$systemd_group" ]
     then
-      last_non_root_user=$(wtmpdb last | sed '/^root/d;s/[ ].*//' | sed -n 1p)
-    else 
-      last_non_root_user=$(last | sed '/^root/d;s/[ ].*//' | sed -n 1p)
+      # Write the Drop-In File
+      write_dropin_file
+
+      # Reload systemd
+      echo "Reloading systemd..."
+      systemctl daemon-reload
+
+      # Update Working Directory Permissions
+      update_working_dir_permissions
+    else
+      echo "Not regenerating ${dropin_file}..."
     fi
-
-    # Now prompt for the user that the service will run as
-    echo "What User should the script run as?"
-    echo " 1. ${last_non_root_user}? [Last Logged In Non-Root User]"
-    echo " 2. root?"
-    echo " 3. Other user?"
-    echo "Take Care if one selects option 3 - The user must exist"
-
-    # Read Users Response
-    read choice
-
-    # Check the Choice is Valid - Continue to Prompt if Not
-    while [ $choice != 1 ] && [ $choice != 2 ] && [ $choice != 3 ]
-    do
-      echo "Invalid Input: [Expected 1, 2, or 3] - Please Retry"
-      read choice
-    done
-
-    # Pick User Name to put in drop-in file
-    if [ $choice == 1 ]; then
-      username="${last_non_root_user}"
-    elif [ $choice == 2 ]; then
-      username="root"
-    elif [ $choice == 3 ]; then
-      echo "Please input the username and press Enter"
-      read username
-
-      # Check username is valid and exists - Prompt again if not
-      while ! id ${username} &> /dev/null
-      do
-        echo "Invalid User input - Please Retry"
-        read username
-      done
-    fi
-
-    # Now get the default group for the username (often the username
-    # again)
-    groupname=$(groups $username | awk '{print $3}')
-
-    # If the dropin directory doesn't exist - create it
-    if [ ! -d "${dropin_dir}" ]
-    then
-      mkdir "${dropin_dir}"
-      echo "Creating Drop-In Directory: ${dropin_dir}"
-    fi
-
-    # Write Drop-In File using above username and groupname
-    write_dropin_file "${username}" "${groupname}"
+  else
+    # Write the Drop-In File
+    write_dropin_file
 
     # Reload systemd
+    echo "Reloading systemd..."
     systemctl daemon-reload
 
-    # Update permissions on Script Dir (if it exists)
-    if [ ! -z "${working_dir}" ] && [ -d "${working_dir}" ]
-    then
-      chown -R $username:$groupname "${working_dir}"
-      chmod -R 775 "${working_dir}"
-      permissions_updated="yes"
-    else
-      permissions_updated="no"
-    fi
+    # Update Working Directory Permissions
+    update_working_dir_permissions
+  fi  
+}
 
-    # Print Brief Instructions on how to start the timer
-    print_instructions
+###################################
+# Write the Drop-In File
+###################################
+write_dropin_file() {
+  echo "Generating ${dropin_file}..."
+  echo "[Service]" > "$dropin_file"
+  echo "User=${systemd_user}" >> "$dropin_file"
+  echo "Group=${systemd_group}" >> "$dropin_file"
+}
 
-  # Drop-In File already exists - just print what user is in it
-  else
-    current_user=$( sed '/User=/!d;s/User=//' "${dropin_file}")
-    echo "Service being ran as ${current_user} - To Change do the following:"
-    echo "  \$ rm "${dropin_file}""
-    echo "  \$ dpkg-reconfigure luadns-ddns"
-    echo ""
-  fi
+###################################
+# Update Working Directory Permissions
+###################################
+update_working_dir_permissions() {
+  echo "Updating permissions on ${working_dir}..."
+  chown "$systemd_user":"$systemd_group" "$working_dir" || \
+  echo "Invalid User/Group Given - please run $ dpkg-reconfigure ${package_name} again"
 }
 
 ###################################
